from . import nexar_client
from . import res_users
from . import component_definition
from . import stock_package_type
from . import product_product
from . import product_template
from . import product_manufacturer
from . import stock_lot
from . import stock_move_line
from . import stock_picking
