{
    'name': 'Product Extra info for FoodArt',
    'version': '12.0.1.0.0',
    'author': 'Rosen Vladimirov, BioPrint Ltd.',
    'website': 'https://github.com/rosenvladimirov/product-attribute',
    'license': 'AGPL-3',
    'category': 'Warehouse',
    'summary': "Add extra information's for FoodArt.",
    'depends': [
        'product',
        'sale_stock',
    ],
    'data': [
        'wizard/product_weight_update_view.xml',
        'views/product_view.xml',
        'views/sale_order_views.xml',
        'views/purchase_views.xml',
        'views/stock_views.xml',
        #'views/account_invoice_view.xml',
        'views/report_invoice.xml',
        'report/report_package_barcode.xml',
        'report/stock_report_views.xml',
        'report/sale_report_templates.xml',
        'report/purchase_order_templates.xml',
    ],
    'installable': True,
}
